#!/usr/bin/env python

import socket

def main():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(("", 7777))
    server.listen(1)

    while True:
        pass

if __name__ == "__main__":
    main()