#!/bin/bash

source /opt/ros/${ROS_DISTRO}/setup.bash

nohup Xvfb ${DISPLAY} -screen 0 ${RESOLUTION} -ac +extension GLX +render -noreset > /dev/null 2>&1 &

nohup startxfce4 > /dev/null 2>&1 &

nohup x11vnc -xkb -noxrecord -noxdamage -display ${DISPLAY} -forever -bg -rfbauth ${HOME}/.vnc/passwd -rfbport ${BOT_VNC_PORT} -users ${BOT_USER} # > /dev/null 2>&1 &

export ROS_MASTER_URI=http://${BOT_HOST}:${ROS_CORE_PORT}
roscore -p ${ROS_CORE_PORT} > /dev/null 2>&1 &

/serial-bridge > /dev/null 2>&1 &

/noVNC/utils/novnc_proxy --vnc ${BOT_HOST}:5900 --listen ${BOT_HOST}:${BOT_PORT} > /dev/null 2>&1 &

cd /app && flask run --host 0.0.0.0 --port ${BOT_SOCKET_PORT}

tail -f /dev/null