default_context:
  name: "bot"
  version: "0.1.0"
  slug: "bot"
  command: "bot"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "n"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "Open Bot"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "open bot"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "bot"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "bot"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/bot"