version: "3.7"

services:
  ros:
    build:
      context: ./docker/ros
      dockerfile: ./alpine/Dockerfile
    image: ${BOT_DOCKER_REGISTRY:-ghcr.io/achillesrasquinha/ros}:core
    volumes:
      - ./shared:/home/bot/shared
      - ./catkin_ws:/home/bot/catkin_ws
    ports:
      - ${BOT_VNC_PORT:-5900}:${BOT_VNC_PORT:-5900}
      - ${BOT_PORT:-8080}:${BOT_PORT:-8080}
      - ${BOT_SOCKET_PORT:-3000}:${BOT_SOCKET_PORT:-3000}
    command: /start
    networks:
      - ros
    environment:
      - BOT_BRIDGE_TCP_HOST=host.docker.internal
      - BOT_HOST=ros

networks:
  ros:
    driver: bridge