version: "3.7"

services:
  ros:
    build:
      context: ./docker/ros
      dockerfile: ./Dockerfile
    image: ${BOT_DOCKER_REGISTRY:-ghcr.io/achillesrasquinha/bot}:core
    volumes:
      - ./shared:/home/bot/shared
    ports:
      - ${BOT_VNC_PORT}:${BOT_VNC_PORT}
    command: /start